import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function RoomOptimised(props) {
  const { nodes, materials } = useGLTF('/models/surroundings/roomtvfinall-opt.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Shading2_cables}
        position={[2.57, -1.384, 1.449]}
        scale={3.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Shading1}
        position={[2.535, 0.03, 0.924]}
        scale={2.918}
      />
      <group position={[2.445, -1.239, 0.461]} scale={2.181}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_1.geometry}
          material={materials.pic2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_2.geometry}
          material={materials.pic3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_3.geometry}
          material={materials.pic4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_4.geometry}
          material={materials.pic5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_5.geometry}
          material={materials.pic6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_6.geometry}
          material={materials.pic7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_7.geometry}
          material={materials.pic8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_8.geometry}
          material={materials.pic9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_9.geometry}
          material={materials.pic10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_10.geometry}
          material={materials.pic11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_11.geometry}
          material={materials.pic12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_12.geometry}
          material={materials.pic13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_13.geometry}
          material={materials.pic14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_14.geometry}
          material={materials.pic15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_15.geometry}
          material={materials.pic16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_16.geometry}
          material={materials.pic17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_17.geometry}
          material={materials.pic18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_18.geometry}
          material={materials.pic19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_19.geometry}
          material={materials.pic20}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_20.geometry}
          material={materials.pic21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_21.geometry}
          material={materials.pic22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_22.geometry}
          material={materials.pic23}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_23.geometry}
          material={materials.pic24}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_24.geometry}
          material={materials.pic25}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_25.geometry}
          material={materials.pic26}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_26.geometry}
          material={materials.pic27}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_27.geometry}
          material={materials.pic28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6_28.geometry}
          material={materials.pic29}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[2.298, -2.888, 1.87]}
        scale={7.697}
      />
    </group>
  );
}

useGLTF.preload('/models/surroundings/roomtvfinall-opt.glb');
