import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function FinalRoom(props) {
  const { nodes, materials } = useGLTF('/models/surroundings/roomTVfinall.glb');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.192}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[10.911, -4.451, 11.013]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Shading2_cables}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.Shading2_cables}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Shading2_cables}
            />
          </group>
          <group position={[10.911, -4.451, 11.013]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Shading1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.Shading1}
            />
          </group>
          <group position={[10.911, -4.451, 11.013]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_1.geometry}
              material={materials.pic2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_2.geometry}
              material={materials.pic3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_3.geometry}
              material={materials.pic4}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_4.geometry}
              material={materials.pic5}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_5.geometry}
              material={materials.pic6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_6.geometry}
              material={materials.pic7}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_7.geometry}
              material={materials.pic8}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_8.geometry}
              material={materials.pic9}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_9.geometry}
              material={materials.pic10}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_10.geometry}
              material={materials.pic11}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_11.geometry}
              material={materials.pic12}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_12.geometry}
              material={materials.pic13}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_13.geometry}
              material={materials.pic14}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_14.geometry}
              material={materials.pic15}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_15.geometry}
              material={materials.pic16}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_16.geometry}
              material={materials.pic17}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_17.geometry}
              material={materials.pic18}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_18.geometry}
              material={materials.pic19}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_19.geometry}
              material={materials.pic20}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_20.geometry}
              material={materials.pic21}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_21.geometry}
              material={materials.pic22}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_22.geometry}
              material={materials.pic23}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_23.geometry}
              material={materials.pic24}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_24.geometry}
              material={materials.pic25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_25.geometry}
              material={materials.pic26}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_26.geometry}
              material={materials.pic27}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_27.geometry}
              material={materials.pic28}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6_28.geometry}
              material={materials.pic29}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_15.geometry}
            material={materials.Shading1}
            position={[10.911, -4.451, 11.013]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.material}
            position={[10.911, -4.451, 11.013]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/surroundings/roomTVfinall.glb');
